AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  # Lambda Function Definition
  SlackNotificationLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "slack-notification4"
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: ./lambda_function/  # Point to the directory containing your Lambda function code
      MemorySize: 128
      Timeout: 300
      Role: !Ref LambdaRoleArn  # Use the pre-configured IAM role
      Environment:
        Variables:
          SLACK_WEBHOOK_URL: !Ref SlackWebhookUrl  # Inject webhook URL from parameter

  # SNS Topic Subscription for Metric Topic
  SnsMetricSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: lambda
      Endpoint: !GetAtt SlackNotificationLambda.Arn
      TopicArn: !Ref SnsMetricTopicArn

  # SNS Topic Subscription for Query Topic
  SnsQuerySubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: lambda
      Endpoint: !GetAtt SlackNotificationLambda.Arn
      TopicArn: !Ref SnsQueryTopicArn

  # Permission for SNS Metric to Invoke Lambda
  LambdaPermissionMetric:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt SlackNotificationLambda.Arn
      Action: "lambda:InvokeFunction"
      Principal: "sns.amazonaws.com"
      SourceArn: !Ref SnsMetricTopicArn

  # Permission for SNS Query to Invoke Lambda
  LambdaPermissionQuery:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt SlackNotificationLambda.Arn
      Action: "lambda:InvokeFunction"
      Principal: "sns.amazonaws.com"
      SourceArn: !Ref SnsQueryTopicArn

Parameters:
  # These are parameters that we can pass during deployment
  SnsMetricTopicArn:
    Type: String
    Description: "The ARN of the metric SNS topic"
    Default: "arn:aws:sns:us-east-1:149451857623:metric-topic"

  SnsQueryTopicArn:
    Type: String
    Description: "The ARN of the query SNS topic"
    Default: "arn:aws:sns:us-east-1:149451857623:query-topic"

  LambdaRoleArn:
    Type: String
    Description: "The ARN of the pre-configured Lambda role"
    Default: "arn:aws:iam::149451857623:role/Lambda_SNS_Role"

  SlackWebhookUrl:
    Type: String
    Description: "The Slack webhook URL for sending notifications"
    Default: "https://hooks.slack.com/services/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"

Outputs:
  LambdaFunctionArn:
    Description: "The ARN of the Lambda function"
    Value: !GetAtt SlackNotificationLambda.Arn
